server:
  port: 8080

app:
  admin:
    username: admin
    password: admin123

google:
  news:
    base-url: "https://news.google.com/rss/search?q="

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DSDataAnalyserDB
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
  mvc:
    static-path-pattern: /**

jwt:
  secret: ddd5Vd8LXtRe0kk234rXwBaW2crrnl1jOZ+1GbWUL5Rw02Y=
  expiration: 3600000

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

openapi:
  dev-url: http://localhost:8080
  prod-url: http://localhost:8080